accounts/urls.py
from django.urls import path

from accounts import views


app_name = "accounts"

urlpatterns=[
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.create_user, name='register'),
    path('changepass/', views.change_pass, name='changepass'),
    path('profile/', views.profile, name='profile')
]

pollme/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('polls/', include('polls.urls', namespace="polls")),
]

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
    path('list/', views.polls_list, name='list'),
    path('list/user/', views.list_by_user, name='list_by_user'),
    path('add/', views.polls_add, name='add'),
    path('edit/<int:poll_id>/', views.polls_edit, name='edit'),
    path('delete/<int:poll_id>/', views.polls_delete, name='delete_poll'),
    path('end/<int:poll_id>/', views.endpoll, name='end_poll'),
    path('edit/<int:poll_id>/choice/add/', views.add_choice, name='add_choice'),
    path('edit/choice/<int:choice_id>/', views.choice_edit, name='choice_edit'),
    path('delete/choice/<int:choice_id>/',
         views.choice_delete, name='choice_delete'),
    path('<int:poll_id>/', views.poll_detail, name='detail'),
    path('<int:poll_id>/vote/', views.poll_vote, name='vote'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class UserRegistrationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100, min_length=5,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Email', max_length=35, min_length=5,
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Password', max_length=50, min_length=5,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Confirm Password',
                                max_length=50, min_length=5,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))

accounts/views.py
import logging
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .forms import UserRegistrationForm
from django.contrib import messages
from django.http import HttpResponse

def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        password = request.POST.get("password")
        try:
            user = authenticate(username=User.objects.get(email=username), password=password)
        except:

            user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            redirect_url = request.GET.get("next", "home")
            return redirect(redirect_url)
        else:
            messages.error(
                request,
                "Username Or Password is incorrect!",
                extra_tags="alert alert-warning alert-dismissible fade show",
            )

    return render(request, "accounts/login.html")


def logout_user(request):
    logout(request)

    return redirect("home")


def create_user(request):
    if request.method == "POST":
        check1 = False
        check2 = False
        check3 = False
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password1 = form.cleaned_data["password1"]
            password2 = form.cleaned_data["password2"]
            email = form.cleaned_data["email"]

            if password1 != password2:
                check1 = True
                messages.error(
                    request,
                    "Password did not match!",
                    extra_tags="alert alert-warning alert-dismissible fade show",
                )
            if User.objects.filter(username=username).exists():
                check2 = True
                messages.error(
                    request,
                    "Username already exists!",
                    extra_tags="alert alert-warning alert-dismissible fade show",
                )
            if User.objects.filter(email=email).exists():
                check3 = True
                messages.error(
                    request,
                    "Email already registered!",
                    extra_tags="alert alert-warning alert-dismissible fade show",
                )

            if check1 or check2 or check3:
                messages.error(
                    request,
                    "Registration Failed!",
                    extra_tags="alert alert-warning alert-dismissible fade show",
                )
                return redirect("accounts:register")
            else:
                user = User.objects.create_user(
                    username=username, password=password1, email=email
                )
                messages.success(
                    request,
                    f"Thanks for registering {user.username}.",
                    extra_tags="alert alert-success alert-dismissible fade show",
                )
                return redirect("accounts:login")
    else:
        form = UserRegistrationForm()
    return render(request, "accounts/register.html", {"form": form})


def change_pass(request):
    if request.user.is_anonymous:
        messages.error(
            request,
            "You need to login",
            extra_tags="alert alert-warning alert-dismissible fade show",
        )

    if request.method == "POST":
        new_pass = request.POST.get("new_pass")
        user = User.objects.get(username=request.user)
        user.set_password(new_pass)
        user.save()
        messages.success(request,"Your password is changed",extra_tags="alert alert-success")
    context = {}
    return render(request, "accounts/set_pass.html", context)


def profile(request):
    user = User.objects.all().get(username = request.user)
    if request.user.is_anonymous:
        return redirect('home')
    
    context = {
        'user' : user ,
        
    }
    return render(request, "accounts/profile.html",context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">

                    <label for="username">Username/Email</label>
                    <input type="text" class="form-control" name="username" placeholder="Enter Username" required>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" name="password" placeholder="Password" required>
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
                <p>Need an account? <a href="{% url 'accounts:register' %}">Register Here</a></p>
            </form>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-5">
    <h1 class="mb-5">Welcome  <kbd>{{ user|title }}</kbd> </h1>
    <a href="{% url 'accounts:changepass' %}" class="btn btn-info btn-block" role="button">Change your password</a>
</div>  
<div class="container mt-5">
  {% comment %} table for showing user info {% endcomment %}
    <table class="table table-dark">
        <tbody>
          <tr>
            <td><kbd>Usename</kbd></td>
            <td class="text-center">{{ user.username }}</td>
          </tr>
          <tr>
          <td><kbd>Email:</kbd></td>
          <td class="text-center">{% if user.email == '' %}NOT SET {% else %}{{ user.email }}{% endif %}</td>
          </tr>
          <tr>
            <td><kbd>Your last login</kbd></td>
            <td class="text-center">{{ user.last_login }}</td>
          </tr>
          <tr>
            <td><kbd>Date of creation:</kbd></td>
            <td class="text-center">{{ user.date_joined }}</td>
          </tr>
          
        </tbody>
    </table>
</div>  

{% endblock content %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            <p>Already have an account? <a href="{% url 'accounts:login' %}">Login Here</a></p>
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Sign Up</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/set_pass.html
{% extends 'base.html' %}
{% block content%}
<div class="container">
    {% for message in messages %}
    <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}<a href="{% url 'accounts:login' %}"
            class="alert-link ml-4" {% if user.is_authenticated %} style="display: none;" {% endif%}class="mb-5">Login</a>
        
    </div>
    {% endfor %}
    <form action="." method="POST" class="form-horizontalmt-5">
        {% csrf_token %}
        <div class="form-group">
            <label class="control-label col-sm-2" for="new_p">New Password</label><br>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="new_p" {%if user.is_anonymous%}placeholder="You must login first" {%else%} placeholder="Enter your new pass" {%endif%}
                    name="new_pass" {% if user.is_anonymous%} disabled {% endif%}><br>
            </div>
        </div>
        <button type="submit" class="btn btn-default btn-info btn-block">Change Password</button>
    </form>
</div>
{% endblock content%}